version: 2

enable-beta-ecosystems: true

updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
     
  - package-ecosystem: "gradle" 
    directory: "/" 
    schedule:
      interval: "weekly"
